name: ninja_typer
description: "A new Flutter project."
version: 1.1.0+1
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.22.0
  flame_audio: ^2.10.6
  get_it: ^8.0.3
  freezed_annotation: ^3.0.0
  firebase_core: ^3.13.0
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  cloud_firestore: ^5.6.6
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  flutter_lints: ^4.0.0
  flame_lint: ^1.2.1
  build_runner: ^2.4.15
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
  fonts:
    - family: MadouFutoMaru
      fonts:
        - asset: assets/fonts/MadouFutoMaruGothic-d9Xo7.ttf
